var tracks = [
    {"name":"Anohana - Secret Base kimi ga kureta mono", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNocXV4MzRqY3RNa28&export=download", "img":"https://i.imgur.com/ckz0JTs.jpg"},
    {"name":"Steins;Gate - Skyclad no Kansokusha", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoVzRRSlUybl8ybW8&export=download", "img":"https://i.imgur.com/BvBRGi0.jpg"},
    {"name":"Boku no Hero Academia - THE DAY", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoXzlxUVQtbTVocm8&export=download", "img":"https://i.imgur.com/jH8PvfS.png"},
    {"name":"Steins;Gate - Hacking to the Gate", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoQTUzUlFvT09xRFk&export=download", "img":"https://i.imgur.com/JfsE08J.jpg"},
    {"name":"Sword Art Online - Crossing field", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoOUlaRnBvZFdHQWc&export=download", "img":"https://i.imgur.com/WTQcYWw.jpg"},
    {"name":"Yuri on Ice - History Maker", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoNy11cHRjX1FoMVE&export=download", "img":"https://i.imgur.com/Vm4Fdj4.png"},
    {"name":"Fairy Tail - Masayume Chasing", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoSFdYSk82V1FiZFk&export=download", "img":"https://i.imgur.com/aPZAYV0.jpg"},
    {"name":"Kekkai Sensen - Sugar Song to Bitter Step", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoWEgwelJlNWxGSGs&export=download", "img":"https://i.imgur.com/DJ5XLiD.jpg"},
    {"name":"Sword Art Online II - Courage", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoRHhxTTFFSzFHeEk&export=download", "img":"https://i.imgur.com/KtCWe1w.jpg"},
    {"name":"Tokyo Ghoul - Unravel", "url":"https://docs.google.com/uc?authuser=0&id=1WNhxmI_1MtX0A4hCcn7_e2X0t86MAbgJ&export=download", "img":"https://i.imgur.com/o186otj.jpg"},
    {"name":"Fairy Tail - Snow Fairy", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoaXV0eFR4eGhlQkU&export=download", "img":"https://i.imgur.com/aPZAYV0.jpg"},
    {"name":"Boku no Hero Academia 3 - Make my story", "url":"https://docs.google.com/uc?authuser=0&id=1p36WhD8GUW7GmXTrQv7IhKOay_ZTxzTl&export=download", "img":"https://i.imgur.com/sXTzC7W.jpg"},
    {"name":"Angel Beats - My Soul Your Beats", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoSHlROWM5aTIwM00&export=download", "img":"https://i.imgur.com/fbkecd8.jpg"},
    {"name":"Diabolik Lovers - Mr Sadistic Night", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoRWJlQXZIWnRqUms&export=download", "img":"https://i.imgur.com/c2p4MB4.png"},
    {"name":"Shingeki no Kyojin 3 - Red Swan", "url":"https://docs.google.com/uc?authuser=0&id=1s6CoggjguTgf7OdPNIPDWfpln2edVYLY&export=download", "img":"https://i.imgur.com/SochbEw.jpg"},
    {"name":"Kimi ni Todoke - Reaching You", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNocVJnT0xWdzFjeDA&export=download", "img":"https://i.imgur.com/Oo4w7ab.png"},
    {"name":"Naruto Shippuuden - Guren", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoLUF5VS1ReTVGaTQ&export=download", "img":"https://i.imgur.com/x9T9MuI.jpg"},
    {"name":"Fullmetal Alchemist - Again", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoME1JaUZxNjJHUzg&export=download", "img":"https://i.imgur.com/bWnVR9d.jpg"},
    {"name":"Inuyasha - Fukai Mori", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoT196SUN0R085RFk&export=download", "img":"https://i.imgur.com/mEeOMk6.jpg"},
    {"name":"Ayashi no Ceres - One", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoekFfbW5UTW5lY2s&export=download", "img":"https://i.imgur.com/LqhIoJo.jpg"},
    {"name":"Your Lie in April - If It Shines", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoX00zWlRzbVJuVjg&export=download", "img":"https://i.imgur.com/oky3In5.jpg"},
    {"name":"Fullmetal Alchemist - Period", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoT0o1aVlwbDhYUjA&export=download", "img":"https://i.imgur.com/tmgRVpf.jpg"},
    {"name":"Shingeki no Kyojin - Die Flugel der Freiheit", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoenN1MFpHNm14MEU&export=download", "img":"https://i.imgur.com/HX58gSZ.png"},
    {"name":"Hunter x Hunter - Hunting for your dream.", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoWkxERjgzalB4emM&export=download", "img":"https://i.imgur.com/cax39mh.jpg"},
    {"name":"Vampire Knight - Futatsu No Kodou To Akai Tsumi", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoc1lQMlNMdkdwYVU&export=download", "img":"https://i.imgur.com/Ett0Sib.jpg"},
    {"name":"Fullmetal Alchemist - Uso", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNodUZrSVAyMjVhS2c&export=download", "img":"https://i.imgur.com/lTz7AaS.jpg"},
    {"name":"Guilty Crown - Euterpe ", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNob08tVmdWYUU1MEU&export=download", "img":"https://i.imgur.com/sXlQI6B.jpg"},
    {"name":"Hunter x Hunter - Departure", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoY3pHZ25QVEx3TTg&export=download", "img":"https://i.imgur.com/nyKXSGe.jpg"},
    {"name":"Naruto Shippuuden - Haruka Kanata", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoS3dQc0ZXYXRvZW8&export=download", "img":"https://i.imgur.com/9kXkEUw.jpg"},
    {"name":"Kekkai Sensen - Hello world", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoV3E4OE5oSDNvMFE&export=download", "img":"https://i.imgur.com/3lVrugZ.png"},
    {"name":"Shingeki no Kyojin - Feuerroter Pfeil und Bogen", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNobHoxNzBZUFRfRXM&export=download", "img":"https://i.imgur.com/jZH1Yli.jpg"},
    {"name":"Sword Art Online - Innocence", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoWGo5R2dPaVFrZHc&export=download", "img":"https://i.imgur.com/0zXF9qV.jpg"},
    {"name":"Shingeki no Kyojin - Great escape", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoQUJ6cmlkTDNUWGc&export=download", "img":"https://i.imgur.com/QZzqOQ0.jpg"},
    {"name":"Dragon Ball Super - Chouzetsu Dynamic", "url":"https://docs.google.com/uc?authuser=0&id=1LfxxbINBnmD4IuHfFFsnTm_j65PyxNyb&export=download", "img":"https://i.imgur.com/nkz61fb.png"},
    {"name":"Nisekoi - ClariS Click", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoUUlJa0w4LXVzejQ&export=download", "img":"https://i.imgur.com/4DMERtm.jpg"},
    {"name":"Kimi no Na wa - Sparkle", "url":"https://docs.google.com/uc?authuser=0&id=1wD4Dur9QUwMat8wrZcIKBdxDd6iyVe_T&export=download", "img":"https://i.imgur.com/8KWf8ew.jpg"},
    {"name":"Fairy Tail - Strike Back", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoMzhwbzRPMHUweWM&export=download", "img":"https://i.imgur.com/rStYwar.jpg"},
    {"name":"Tokyo Ghoul:RE - Asphyxia", "url":"https://docs.google.com/uc?authuser=0&id=1qgC4EQTV-GOHlWYzqDaCdI4ZzHTjauK8&export=download", "img":"https://i.imgur.com/jO117VP.jpg"},
    {"name":"Toradora - Pre Parade", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoTDIyS3lFVlhvMDA&export=download", "img":"https://i.imgur.com/FMsZlYh.jpg"},
    {"name":"Guilty Crown - My Dearest", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoT3RUUHBlSE5KVGs&export=download", "img":"https://i.imgur.com/C9L9IGU.jpg"},
    {"name":"Anohana - Aoi Shiori Blue Bookmark", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNodDFuOEY0V1BCU0U&export=download", "img":"https://i.imgur.com/XZdn2IH.jpg"},
    {"name":"One Punch Man - THE HERO!!", "url":"https://docs.google.com/uc?authuser=0&id=10Ek2HiU3YTeonsTfY4vtDXw5iAiebQtc&export=download", "img":"https://i.imgur.com/mGt1dfn.jpg"},
    {"name":"Amnesia Zoetrope", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoOEJsWmZybUNZN2M&export=download", "img":"https://i.imgur.com/5UJ61Xv.jpg"},
    {"name":"Fairy Tail - Kimi ga iru kara", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoQlJ3UDlUUmZXLXM&export=download", "img":"https://i.imgur.com/uwW42GR.jpg"},
    {"name":"Gintama - Pray Tommy Heavenly", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoekw0NVJ0N3A0R3c&export=download", "img":"https://i.imgur.com/SGN3GaX.jpg"},
    {"name":"Boku no Hero Academia 3 - ODD FUTURE", "url":"https://docs.google.com/uc?authuser=0&id=1B34UKdpgLReAORIX0D4pebqpD3VMOLx-&export=download", "img":"https://i.imgur.com/pn1ckaN.png"},
    {"name":"Brothers Conflict", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoVGxYTnFzLUJDc1k&export=download", "img":"https://i.imgur.com/1wKzRCN.jpg"},
    {"name":"Fairy Tail - Towa no Kizuna", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNodjJ4aGdkQlVQS1k&export=download", "img":"https://i.imgur.com/ihIqbsA.jpg"},
    {"name":"Sword Art Online - Yume Sekai", "url":"https://docs.google.com/uc?authuser=0&id=0B_WN56ek5XNoQU5tVDY4NUJWT0k&export=download", "img":"https://i.imgur.com/iccXJQ8.jpg"},
    {"name":"Dummy Song - dum dum", "url":"https://foo.foo", "img":"https://i.imgur.com/iccXJQ8.jpg"}
];  